package com.ndjc.app.analytics

object AnalyticsConfig {
    // NDJC:ANALYTICS_DSN
    // NDJC:ANALYTICS_EVENTS_MAP
    // NDJC:ANALYTICS_USER_ID_KEY
    // NDJC:CRASH_DSN
    // NDJC:CRASH_COLLECTION_ENABLED
    // NDJC:DEBUG_LOGGING_ENABLED
}
