package com.ndjc.app.work
// NDJC:BLOCK:WORK_MANAGER
// NDJC:BLOCK:FOREGROUND_SERVICE
// NDJC:WORK_NAME  => 由 BuildConfig.WORK_NAME 提供
// NDJC:WORKER_RETRIES
// NDJC:WORKER_RETRY_STRATEGY
// NDJC:WORK_CONSTRAINTS
// NDJC:WORK_INTERVAL_MINUTES
