name: Android Debug Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      runId:
        description: "NDJC run id (for tracing)"
        type: string
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        working-directory: app
        run: chmod +x ./gradlew

      - name: Build Debug APK
        working-directory: app
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
