name: Android Debug Build
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 仅做 Gradle 缓存/初始化；真正执行要用 run: ./gradlew ...
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 可选：保留你现有的“写入 ndjc_info.json”和“准备 debug.keystore”的脚本
      # - name: Write NDJC info asset + request logs
      #   run: |
      #     # 你的脚本…

      # - name: Ensure debug keystore
      #   run: |
      #     # 你的脚本…

      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon clean assembleDebug
          echo "=== APKs produced ==="
          ls -lah app/build/outputs/apk/debug || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
