name: Test Manual Trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'App name'
        required: false
        default: 'Test App'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello ${{ github.event.inputs.name }}"
