name: Build One Template APK

on:
  workflow_dispatch:
    inputs:
      template:
        description: 'Template name (simple-template / core-template / form-template)'
        required: false
        default: 'simple-template'
  push:
    paths:
      - 'templates/**'
      - '.github/workflows/build-one.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select template
        run: |
          TEMPLATE_NAME=${{ github.event.inputs.template || 'simple-template' }}
          echo "Using template: $TEMPLATE_NAME"

          # 删除旧 app 目录
          rm -rf app
          
          # 拷贝 templates 下的指定模板的 app 目录到根目录
          cp -r templates/$TEMPLATE_NAME/app app
          echo "Template copied successfully."

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
