name: Init Gradle Wrapper
on:
  workflow_dispatch: {}   # 只手动触发，避免每次 push 都跑

jobs:
  add-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 给各模板目录生成 wrapper（按你的目录结构改）
      - name: Generate wrapper (core)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2'
          arguments: wrapper
          build-root-directory: templates/core-template

      - name: Generate wrapper (simple)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2'
          arguments: wrapper
          build-root-directory: templates/simple-template

      - name: Generate wrapper (form)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2'
          arguments: wrapper
          build-root-directory: templates/form-template

      - name: Commit wrapper files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add Gradle wrapper to each template"
          file_pattern: |
            templates/**/gradlew
            templates/**/gradlew.bat
            templates/**/gradle/wrapper/*
