name: Init Gradle Wrapper

on:
  # 手动触发
  workflow_dispatch:

  # 也可以在你改动模板目录时自动触发（可按需保留/删除）
  push:
    paths:
      - 'templates/**'

permissions:
  contents: write  # 允许自动提交生成的 wrapper

jobs:
  add-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 这里用 gradle/gradle-build-action@v3 直接调用 `wrapper` 任务。
      # 加 --no-search-upward 防止向上查找根 settings.gradle 造成 “not part of the build defined by settings file” 报错
      - name: Generate wrapper (core)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2'
          build-root-directory: templates/core-template
          arguments: wrapper --no-daemon --no-search-upward

      - name: Generate wrapper (simple)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2'
          build-root-directory: templates/simple-template
          arguments: wrapper --no-daemon --no-search-upward

      - name: Generate wrapper (form)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2'
          build-root-directory: templates/form-template
          arguments: wrapper --no-daemon --no-search-upward

      # 给 gradlew 增加可执行权限（Windows 的 .bat 不需要）
      - name: Make gradlew executable
        run: |
          chmod +x templates/*-template/gradlew || true

      # 自动提交生成的 wrapper 文件
      - name: Commit and push wrappers
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: add/update Gradle wrapper for templates'
          file_pattern: |
            templates/**/gradlew
            templates/**/gradlew.bat
            templates/**/gradle/wrapper/**
