name: init-gradle-wrapper
on:
  workflow_dispatch:

permissions:
  contents: write  # 允许提交到仓库

jobs:
  add-wrapper:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: [core-template, simple-template, form-template]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) 下载一个 Gradle（只用来生成 wrapper，不会解析你的工程）
      - name: Download Gradle 8.2
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.2-bin.zip -O gradle.zip
          unzip -q gradle.zip

      # 2) 在临时目录创建一个超小的构建，只注册 wrapper 任务
      - name: Generate wrapper in a temp project
        id: gen
        run: |
          TMP="$(mktemp -d)"
          cat > "$TMP/build.gradle" <<'EOF'
          tasks.register('wrapper', Wrapper) {
            gradleVersion = '8.2'
            distributionType = Wrapper.DistributionType.ALL
          }
          EOF
          ./gradle-8.2/bin/gradle -p "$TMP" wrapper --no-daemon
          echo "TMP=$TMP" >> $GITHUB_OUTPUT

      # 3) 把生成的 wrapper 复制到各模板根目录并提交
      - name: Copy wrapper into template and commit
        run: |
          set -e
          TEMPL_DIR="templates/${{ matrix.template }}"
          TMP="${{ steps.gen.outputs.TMP }}"

          mkdir -p "$TEMPL_DIR/gradle/wrapper"
          cp "$TMP/gradlew" "$TEMPL_DIR/gradlew"
          cp "$TMP/gradlew.bat" "$TEMPL_DIR/gradlew.bat"
          cp "$TMP/gradle/wrapper/"* "$TEMPL_DIR/gradle/wrapper/"

          git add "$TEMPL_DIR/gradlew" \
                  "$TEMPL_DIR/gradlew.bat" \
                  "$TEMPL_DIR/gradle/wrapper/gradle-wrapper.jar" \
                  "$TEMPL_DIR/gradle/wrapper/gradle-wrapper.properties"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Add Gradle wrapper to ${{ matrix.template }}" || echo "nothing to commit"
          git push
