name: init-gradle-wrapper

on:
  workflow_dispatch: {}

jobs:
  add-wrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 这里不再用 --no-search-upward
      - name: Generate wrapper (core)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.2
          build-root-directory: templates/core-template
          arguments: wrapper --no-daemon

      - name: Generate wrapper (simple)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.2
          build-root-directory: templates/simple-template
          arguments: wrapper --no-daemon

      - name: Generate wrapper (form)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.2
          build-root-directory: templates/form-template
          arguments: wrapper --no-daemon

      - name: Make gradlew executable
        run: |
          git update-index --chmod=+x templates/*-template/gradlew
          git status --porcelain

      - name: Commit wrapper files
        run: |
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add templates/*-template/gradlew templates/*-template/gradlew.bat templates/*-template/gradle/wrapper/*
            git commit -m "chore: add Gradle wrapper for templates"
            git push
          else
            echo "No changes to commit."
          fi
