name: Init Gradle Wrapper
on:
  workflow_dispatch: {}

jobs:
  add-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 为每个模板生成 wrapper（按你的模板路径改）
      - name: Generate wrapper (core)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2'      # 和你日志里一致的 8.2，保持稳定
          arguments: wrapper
        working-directory: templates/core-template

      - name: Generate wrapper (simple)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2'
          arguments: wrapper
        working-directory: templates/simple-template

      - name: Generate wrapper (form)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.2'
          arguments: wrapper
        working-directory: templates/form-template

      - name: Commit wrapper files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add Gradle wrapper to each template"
          file_pattern: |
            templates/**/gradlew
            templates/**/gradlew.bat
            templates/**/gradle/wrapper/*
