name: Release APK

on:
  # 手动触发（可自定义 tag）
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (optional)"
        required: false
  # 构建成功后自动触发
  workflow_run:
    workflows: ["Android Build (3 Templates Matrix)"]  # 改成你构建工作流的名字
    types: [completed]

permissions:
  contents: write   # 关键：允许写 Release

jobs:
  release:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-core-template
          path: dist

      - name: Ensure APK present
        run: |
          ls -l dist || true
          test -n "$(ls -1 dist/*.apk 2>/dev/null)" || { echo "No APK found"; exit 1; }

      - name: Compute checksums
        run: |
          cd dist
          for f in *.apk; do sha256sum "$f" >> SHA256SUMS.txt; done
          cat SHA256SUMS.txt

      - name: Decide tag
        id: tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
          else
            # 自动场景：用 run_number 生成递增 tag；也可换成日期/commit 前缀
            echo "tag=v${{ github.run_number }}" >> "$GITHUB_OUTPUT"
          fi

      # 主上传：支持 allowUpdates / replacesArtifacts
      - name: Upload to Release (primary)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          allowUpdates: true
          makeLatest: true
          replacesArtifacts: true
          artifacts: "dist/*.apk,dist/SHA256SUMS.txt"
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

      # 兜底上传：主步骤失败才走（为避免网络抖动/偶发 5xx）
      - name: Upload fallback (softprops)
        if: failure()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          files: |
            dist/*.apk
            dist/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 上传后验证：确保 Release 确实有资产
      - name: Verify assets attached
        uses: actions/github-script@v7
        with:
          script: |
            const tag = '${{ steps.tag.outputs.tag }}';
            const { owner, repo } = context.repo;
            const rel = await github.rest.repos.getReleaseByTag({ owner, repo, tag });
            const assets = rel.data.assets || [];
            core.info(`Assets count: ${assets.length}`);
            if (!assets.length) core.setFailed('No assets found on Release!');
